In [57]:
from numpy import *
import operator

def createDataSet():
    group = array([[1.0, 1.1], [1.0, 1.0], [0, 0], [0, 0.1]])
    labels = ['A', 'A', 'B', 'B']
    return group, labels

In [58]:
group,labels = createDataSet()

In [59]:
group

array([[ 1. ,  1.1],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 0. ,  0.1]])

In [60]:
labels

['A', 'A', 'B', 'B']

In [63]:
def knn(inX, dataSet, labels, k):
    # 矩阵计算。 计算待测数据与已有样本的距离
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize, 1)) - dataSet
    sqDiffMat = diffMat ** 2
    sqDistances = sqDiffMat.sum(axis = 1)
    distances = sqDistances ** 0.5
    sortedDistIndicies = distances.argsort()
    classCount = {}
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
    sortedClassCount = sorted(classCount.iteritems(), key = operator.itemgetter(1), reverse = True)
    return sortedClassCount[0][0]

In [7]:
inX = [1.2, 0.9]

In [14]:
groupSize = group.shape[0]

In [16]:
diffMat = tile(inX, (groupSize, 1)) - group

In [19]:
sqDiffMat = diffMat ** 2

In [24]:
sqDistances = sqDiffMat.sum(axis=1)

In [48]:
distances = sqDistances ** 0.5
distances

array([ 0.28284271,  0.2236068 ,  1.5       ,  1.44222051])

In [53]:
sortedDistIndicies = distances.argsort()
sortedDistIndicies

array([1, 0, 3, 2], dtype=int64)

In [ ]:
def autoNorm(dataSet):
    minVals = dataSet.min(0)
    maxVals = dataSet.max(0)
    ranges = maxVals - minVals
    normDataSet = zeros(shape(dataSet))
    m = dataSet.shape[0]
    normDataSet = dataSet - tile(minVals, (m, 1))
    normDataSet = normDataSet / tile(ranges, (m, 1))
    return normDataSet, rang